source/apiVolontaria/apiVolontaria/tests/tests_ObtainTemporaryAuthToken.py, source/apiVolontaria/apiVolontaria/tests/tests_view_ObtainTemporaryAuthToken.py
| Type of contribution ?                      | [Fix, Enhancement]
| Tickets (_issues_) concerned               | [none]
---
- Added an authentication test (expired token use case)
- Test file renamed according to convention
Test does this:
1. Authenticate a user (that creates a new TemporaryToken)
2. Expires the token
3. Re-authenticate the user (should get a new token)
4. Verifies that the expired token is not in the response of step 3
5. Verifies that a new token is in the response instead of step 3
Verification :
-  [ ] My branch name respect the standard defined in `CONTRIBUTING.md` 
- Where is it??
-  [X] This Pull-Request fully …
=> Expired token authentication test

source/apiVolontaria/apiVolontaria/settings.py
| Tickets (_issues_) concerned               | fixed #9 
---
I've configured the pagination on the project.
I've add two lines of configuration in the `settings.py` file like explain in [this documentation of DRF](http://www.django-rest-framework.org/api-guide/pagination/)
Verification :
-  [ ] My branch name respect the standard defined in `CONTRIBUTING.md`
=> add standard pagination of DRF

source/apiVolontaria/apiVolontaria/tests/tests_model_TemporaryToken.py
| Tickets (_issues_) concerned               | No one
---
Test the `TemporaryToken` model
- Add a new file `tests_model_TemporaryToken`
- Add two use case on `expired` property
- Add a use case on `expire()` method
Verification :
-  [ ] My branch name respect the standard defined in `CONTRIBUTING.md`
=> add test on TemporatyToken model

.travis.yml, requirements-dev.txt
| Type of contribution ?                      | [Enhancement]
| Tickets (_issues_) concerned               | fixes #13
---
- Added `requirements-dev.txt` file
- Switch Travis to pycodestyle
Verification :
-  [ ] My branch name respect the standard defined in `CONTRIBUTING.md`
=> Adds requirements-dev and switch to pycodestyle

docs/CODE_OF_CONDUCT.md
| Tickets (_issues_) concerned               | fixed #24  
---
Add a new code of conduct
Get the default templates of github for all kind of organization.
Creation of the file on `/docs/` to be detected by `Github` and `ReadTheDoc`
Verification :
=> add CODE_OF_CONDUCT.md

docs/CONTRIBUTING.md
| Type of contribution ?                      | [Documentation]
| Tickets (_issues_) concerned               | fixed #14
---
Add a contribution document describing guidelines for new contributors
New file named docs/CONTRIBUTING.md
Verification :
-  [X] I added or modified the attached tests
=> Add a contributing documentation

source/apiVolontaria/apiVolontaria/settings.py
| Tickets (_issues_) concerned               | fixed #37
---
Add STATIC_ROOT base settings in settings.py
Verification :
=> Add STATIC_ROOT base setting in settings.py

.gitignore, docs/Tutorial/Quickstart.md, source/apiVolontaria/apiVolontaria/local_settings.py, source/apiVolontaria/apiVolontaria/settings.py
| Tickets (_issues_) concerned               | Fixed #33
---
I have added a local_settings file to overwrite the global settings for local purpose.
I have added a file local_settings_example.py file that import the settings.py file and make it possible ta have custom settings depending on the actual env.  The user must make a copy of local_settings_example.py to local_settings.py in the same folder.
Verification :
-  [ ] I added or …
=> Add local_settings feature

source/apiVolontaria/apiVolontaria/settings.py
| Tickets (_issues_) concerned               | None
---
Fix cross-origin call 
Add a middleware forgotten at the init of the project.
Verification :
-  [ ] This Pull-Request fully meets the requirements defined in the issue
=> add CorsMiddleware to allow cros origin

source/apiVolontaria/volunteer/serializers.py, source/apiVolontaria/volunteer/tests/tests_view_Events.py, source/apiVolontaria/volunteer/tests/tests_view_EventsId.py
| Tickets (_issues_) concerned               | None
---
Add details on EventSerializer to reduce the number of call from the frontend
Usage of NestedSerializers
Usage of new SerializerField to edit nested field
Verification :
-  [ ] This Pull-Request fully meets the requirements defined in the issue
=> add detail on eventSerializer

source/apiVolontaria/apiVolontaria/serializers.py, source/apiVolontaria/apiVolontaria/tests/tests_view_UsersId.py, source/apiVolontaria/apiVolontaria/views.py
| Type of contribution ?                      | Feature
| Tickets (_issues_) concerned               | Fixes #68 
---
Add the  possibility for users to change their informations. 
Added a PATCH endpoint to allow user to update their informations.
Verification :
=> Feature password change

source/apiVolontaria/volunteer/models.py, source/apiVolontaria/volunteer/tests/tests_model_Cycle.py, source/apiVolontaria/volunteer/tests/tests_model_TaskType.py
| Tickets (_issues_) concerned               | Fixes #40 
---
Added a method to enable a custom string representation of all models.
Added str() method on TaskType, Cycle and TemporaryToken.
Verification :
=> Fix missing str method

source/apiVolontaria/apiVolontaria/serializers.py, source/apiVolontaria/apiVolontaria/tests/tests_view_Users.py
| Tickets (_issues_) concerned               | none
---
Added validation of phone numbers fields in the serializer. The API now returns a meaningful error message. (We only had validation at model level.)
Added a custom validator for phone numbers.
Verification :
=> Bug profile phone validation

source/apiVolontaria/location/views.py, source/apiVolontaria/volunteer/views.py
| Tickets (_issues_) concerned               | fixed #50 
---
I've corrected the `update()` to `partial_update()`
...
Verification :
=> update views for change update to partial_update

source/apiVolontaria/volunteer/admin.py, source/apiVolontaria/volunteer/models.py, source/apiVolontaria/volunteer/tests/tests_model_Participation.py
| Tickets (_issues_) concerned               | fixed #87 
---
Add filters and search bar on the participation's admin panel
- Create a `ParticipationAdmin` implementation of `admin.ModelAdmin` to overwrite the default admin panel.
- Create some property in the `Participation` model.
Verification :
=> upgrade of participation's admin panel

source/apiVolontaria/apiVolontaria/locale/en/LC_MESSAGES/django.po, source/apiVolontaria/apiVolontaria/locale/fr/LC_MESSAGES/django.po, source/apiVolontaria/apiVolontaria/settings.py, source/apiVolontaria/apiVolontaria/views.py, source/apiVolontaria/location/locale/en/LC_MESSAGES/django.po, source/apiVolontaria/location/locale/fr/LC_MESSAGES/django.po, source/apiVolontaria/location/views.py, source/apiVolontaria/volunteer/locale/en/LC_MESSAGES/django.po, source/apiVolontaria/volunteer/locale/fr/LC_MESSAGES/django.po, source/apiVolontaria/volunteer/views.py
| Tickets (_issues_) concerned               | fixed #72
---
We configure the DRF translation system
Add some settings
Generate PO file
Add `ugettext_lazy` on view error message
We tried to add some test but headers doesn't work on test. We discussed this problem with @francisjeanneau  and we will open a new issue to add these tests.
Verification :
=> init translate message error

source/apiVolontaria/apiVolontaria/admin.py
| Tickets (_issues_) concerned               | fixed #130
---
Small modification to the admin.py
Applied this [solution](https://stackoverflow.com/questions/43620609/django-edit-useradmin-removes-change-password-form-from-admin-site)
Verification :
=> Add the change password form in the User admin panel.

source/apiVolontaria/volunteer/admin.py
| Tickets (_issues_) concerned               | fixed #127
---
Simply add filtering and date_hierarchy to Participation admin
Verification :
=> Add Filtering to Participation Admin

source/apiVolontaria/apiVolontaria/admin.py
| Tickets (_issues_) concerned               | fixed #139
---
I have added the Profile informations in the User admin panel.
Verification :
=> Add Profile model informations into User admin panel

source/apiVolontaria/apiVolontaria/serializers.py, source/apiVolontaria/apiVolontaria/tests/tests_view_Users.py
| Tickets (_issues_) concerned               | fixed #102 
---
I added some required field to create a new account from the API
- Add some logic in the user's serializer
- Update tests
Verification :
=> change required field to create an account

source/apiVolontaria/volunteer/admin.py, source/apiVolontaria/volunteer/tests/tests_admin_Participation.py
| Tickets (_issues_) concerned               | fixed #134
---
In Participations admin panel:
- Upgrade list_display
- Upgrade search_fields
- Add ordering by event start_date
Verification :
-  [X] I added or modified the attached tests
=> Search by first_name/last_name/email in Participations admin

source/apiVolontaria/volunteer/admin.py, source/apiVolontaria/volunteer/tests/tests_admin_EventAdmin.py
| Tickets (_issues_) concerned               | fixed #145
---
Add an AdminEvent class with basic admin customization
Verification :
-  [X] I added or modified the attached tests
=> Upgrade event admin

.github/PULL_REQUEST_TEMPLATE.md
| Tickets (_issues_) concerned               | fixed #23 
---
Add some check to help contributor to create new PRs.
Add a checklist in the PR template to easily check important part of the contribution
Verification :
=> add important check in PR template

source/apiVolontaria/volunteer/tests/tests_view_Events.py, source/apiVolontaria/volunteer/views.py
| Tickets (_issues_) concerned               | Closes #75 
---
Added possibility to filter events GET with query parameters.
Updated get_queryset() method of the view
Verification :
=> Enhancement event filter by cycle

source/apiVolontaria/volunteer/tests/tests_view_Events.py, source/apiVolontaria/volunteer/views.py
| Tickets (_issues_) concerned               | fixed #164
---
Add a filter by `cell` when get the list of events.
Add a filter on the `events` list view
Add some tests
=> Enhancement add cell filter on events list

source/apiVolontaria/volunteer/tests/tests_view_Participations.py, source/apiVolontaria/volunteer/views.py
| Tickets (_issues_) concerned               | fixed #166
---
Add a filter by event on participations listing
Add a filter on the view
=> Enhancement allow user to filter participations by event

source/apiVolontaria/volunteer/serializers.py, source/apiVolontaria/volunteer/tests/tests_view_Participations.py, source/apiVolontaria/volunteer/tests/tests_view_ParticipationsId.py
| Tickets (_issues_) concerned               | fixed #168 
---
Add user info in participation list and detail
Add a nested user's serializer in the participation's serializer
=> Enhancement update participation serializer to get user detail

.gitignore
| Tickets (_issues_) concerned               | Fixed #170
---
Add the file to .gitignore
=> Add the local_settings to the ignore file

requirements.txt, source/apiVolontaria/apiVolontaria/settings.py, source/apiVolontaria/volunteer/admin.py, source/apiVolontaria/volunteer/resources.py, source/apiVolontaria/volunteer/tests/tests_admin_participation_export.py
| Tickets (_issues_) concerned               | Fixed #148
---
I have added the possibility to export a report from the admin panel
Added the [django-import-export](https://github.com/django-import-export/django-import-export) tool.
=> Add exportation options to Participations admin

source/apiVolontaria/volunteer/admin.py, source/apiVolontaria/volunteer/models.py, source/apiVolontaria/volunteer/tests/tests_admin_Cycle.py, source/apiVolontaria/volunteer/tests/tests_model_Cycle.py
| Tickets (_issues_) concerned               | Fixed #154
---
Added the possibility to export a report in csv format from the admin panel.
I have added an admin action to compile the hours of the volunteer
=> Exportation of the Participations of a Cycle

requirements.txt
| Tickets (_issues_) concerned               | None
---
Changer Django version
Change version in `requirements.txt` file
=> change django version from 1.11.10 to 1.11.12

requirements-dev.txt, tests.py
| Tickets (_issues_) concerned               | #32 
---
Add a new test script to help contributor check their code in locale without Travis and Coveralls
Feel free to play with command of the third bullet to test.
1. Create a new class `Test` in a file named `tests.py`
2. Create a modular test system with method detection 
- Each method that begin with `__command_` is considering as a potential command we can launch to test
3. Add some options on commandline
- `python tests` : Run all tests
- `python tests [command [command]]` : Run one or multiple command
- `python tests [help | h | …
=> add local test script

source/apiVolontaria/apiVolontaria/serializers.py, source/apiVolontaria/apiVolontaria/tests/tests_view_Users.py, source/apiVolontaria/apiVolontaria/tests/tests_view_UsersId.py, source/apiVolontaria/volunteer/tests/tests_model_Cycle.py
| Tickets (_issues_) concerned               | Fixed #184
---
Add a role field in the user serializer to have a list of roles
=> Add roles to the user serializer

source/apiVolontaria/volunteer/serializers.py, source/apiVolontaria/volunteer/tests/tests_view_Events.py
| Tickets (_issues_) concerned               | https://genielibre.com/issues/61
---
Add some check on event date during creation
- Add a validator in the Event's serializer
- Add some tests
=> Fix error 500 on API creation event 

source/apiVolontaria/apiVolontaria/locale/en/LC_MESSAGES/django.po, source/apiVolontaria/apiVolontaria/locale/fr/LC_MESSAGES/django.po, source/apiVolontaria/location/locale/en/LC_MESSAGES/django.po, source/apiVolontaria/location/locale/fr/LC_MESSAGES/django.po, source/apiVolontaria/volunteer/locale/en/LC_MESSAGES/django.po, source/apiVolontaria/volunteer/locale/fr/LC_MESSAGES/django.po
| Type of contribution ?                      | Documentation
| Tickets (_issues_) concerned               | [8](https://genielibre.com/issues/8)
---
Fill PO header to correctly init file.
Just change the text with a little bash command:
`find source/ -type f -name '*.po' -exec sed -e s'/old text/new text/g' -i {} \;`
=> init PO header with some data

source/apiVolontaria/volunteer/tests/tests_view_Cells.py, source/apiVolontaria/volunteer/views.py
| Type of contribution ?                      | [Enhancement]
| Tickets (_issues_) concerned               | [[92]](https://genielibre.com/issues/92)
---
The ordering of the cell to have them listed alphabetically
=> Add ordering to cell model

source/apiVolontaria/volunteer/models.py, source/apiVolontaria/volunteer/permissions.py, source/apiVolontaria/volunteer/tests/tests_view_CellsId.py, source/apiVolontaria/volunteer/tests/tests_view_Events.py, source/apiVolontaria/volunteer/tests/tests_view_EventsId.py, source/apiVolontaria/volunteer/tests/tests_view_ParticipationsId.py, source/apiVolontaria/volunteer/views.py
| Tickets (_issues_) concerned               | https://genielibre.com/issues/60
---
Add access to manager of Cell to change their Participation
Review the permissions and modify the view
=> Access to Cell Manager to update a Participation and manage Events

requirements.txt, source/apiVolontaria/apiVolontaria/settings.py, source/apiVolontaria/apiVolontaria/tests/tests_view_UsersId.py, source/apiVolontaria/apiVolontaria/urls.py, source/apiVolontaria/location/urls.py, source/apiVolontaria/volunteer/models.py, source/apiVolontaria/volunteer/tests/tests_admin_Cycle.py, source/apiVolontaria/volunteer/tests/tests_view_Events.py, source/apiVolontaria/volunteer/tests/tests_view_ParticipationsId.py, source/apiVolontaria/volunteer/urls.py
| Tickets (_issues_) concerned               | [#215](https://genielibre.com/issues/215)
---
Upgrade Django from 1.11 to 2.1.3
Change requirements
Fix `on_delete` arguments in FK models
Fix Urls
=> migration to django 2

docs/Tutorial/Quickstart.md
| Type of contribution ?                      | Documentation
| Tickets (_issues_) concerned               | None
---
- Add a section to create a new administrator
- Add some details to get the good link to clone
Just update the `Quickstart.md` file
=> add some details on install documentation

source/apiVolontaria/apiVolontaria/tests/tests_view_Users.py, source/apiVolontaria/apiVolontaria/views.py
| Type of contribution ?                      | [Enhancement]
| Tickets (_issues_) concerned               | [[221](https://genielibre.com/issues/221)]
---
Add http query param search to the GET user
Will search username, first_name, last_name, email that start with search sended (ignoring case).
=> Add query params to users GET

source/apiVolontaria/volunteer/resources.py, source/apiVolontaria/volunteer/serializers.py, source/apiVolontaria/volunteer/tests/tests_view_Cell_Exportation.py, source/apiVolontaria/volunteer/views.py
| Type of contribution ?                      | [Enhancement]
| Tickets (_issues_) concerned               | [[76]](https://genielibre.com/issues/76)
---
Add filtering for Cycle and TaskType to the CellExportSerializer 
=> Add filtering option when exportation Participations
